version: '3.9'

services:
  server:
    build: .
    ports:
      - "8083:8082"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432 
      POSTGRES_DB: 'postgres'  
  db:
    image: 'postgres'
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER : 'postgres'
      POSTGRES_PASSWORD : 'root' 


